version: "3.7"

services:
  web:
    image: httpd
    ports:
      - "80:80"
    volumes:
      - ./:/usr/local/apache2/htdocs

    networks:
      - minha-rede

networks:
   minha-rede:
     driver: bridge
